# =============================================================================
# Bilibili 超级下载器配置文件
# =============================================================================
# 融合版本：完全对标 bup-scan-xlsx-bbdown-v3.py 和 bili-down-batch.py
# 工作模式：
# - Single模式: 深度抓取单个UP主，支持Excel进度保存
# - Batch模式:  批量处理多个UP主，快速更新最新视频

# =============================================================================
# 基础配置 (Base Configuration)
# =============================================================================
base:
  # 工作模式: single(单UP主) | batch(批量) 
  mode: "batch"
  
  # 数据存储目录
  data_dir: "D:/bilibili/data"
  
  # 视频下载目录 (所有视频将下载到此目录的子文件夹中)
  download_dir: "D:/bilibili"
  
  # Excel文件路径 (仅single模式使用，保存视频进度信息)
  excel_file_path: "D:/bilibili/data/bilibili_videos.xlsx"
  
  # 日志级别: DEBUG | INFO | WARNING | ERROR
  log_level: "INFO"

# =============================================================================
# 认证配置 (Authentication) - 必填项
# =============================================================================
auth:
  # B站Cookie (从浏览器开发者工具获取)
  # ⚠️  重要安全提醒：请替换为您自己的Cookie信息
  # ⚠️  该信息包含敏感认证数据，请勿分享或提交到公共仓库
  cookie: "YOUR_BILIBILI_COOKIE_HERE"

# =============================================================================
# UP主配置 (Uploader Configuration)
# =============================================================================
uploader:
  # 单UP主模式配置 (仅single模式使用)
  single_mid: "586631367"
  
  # 批量模式UP主列表 (仅batch模式使用)
  # 格式: 文件夹名: UP主ID (将创建"Bili-{文件夹名}"目录)
  batch_list:
    幻塔: "586631367"


# =============================================================================
# 时间配置 (Time Configuration)
# =============================================================================
time:
  # 增量下载起始日期 (仅single模式使用)
  # 格式: "2024-01-01" 或留空表示获取所有视频
  start_date: ""
  
  # 批量模式时间范围 (仅batch模式使用)
  # 数字表示最近N天，例如: "7"表示最近7天
  batch_time_range: "7"

# =============================================================================
# 下载配置 (Download Configuration)
# =============================================================================
download:
  # 下载开关 (true=下载视频, false=仅获取信息)
  enabled: true
  
  # 检查已下载视频 (true=跳过已存在文件)
  check_downloaded: true
  
  # 最大下载线程数 (建议保持1，避免触发限制)
  max_workers: 1
  
  # 清理下载目录中的子文件夹
  clean_subfolders: true
  
  # 清理临时文件 (.download, .part, .tmp等)
  clean_temp_files: true

# =============================================================================
# 网络配置 (Network Configuration)
# =============================================================================
network:
  # 是否启用随机User-Agent (建议保持false，对标服务器版本)
  use_random_ua: false
  
  # 请求间延迟时间(秒) - 对标服务器版本的time.sleep(1)
  delay: 1.0
  
  # 最大抓取页数 (防止无限循环)
  max_pages: 100
  
  # 每页视频数量 (B站API限制最大50)
  page_size: 50
  
  # 请求超时时间(秒)
  timeout: 10
  
  # SSL验证 (false=忽略SSL证书验证)
  verify_ssl: false

# =============================================================================
# 数据配置 (Data Configuration) - 仅single模式使用
# =============================================================================
data:
  # 数据存储格式 (仅single模式使用，保持v3版本的Excel格式)
  format: "excel"
  
  # Excel工作表名称
  sheet_name: "Videos"
  
  # 是否包含索引列
  include_index: false
  
  # 断点续传增强配置
  split_by_uploader: true  # 按UP主ID分表存储 (推荐开启)
  excel_pattern: "bilibili_videos_{mid}_{date}.xlsx"  # 分表文件命名模式